name: layou_user_avatar
description: A customizable Flutter package for user avatar management with Firebase, Riverpod, WebP conversion, and caching.
version: 0.1.3
repository: https://github.com/yelkamel/layou_user_avatar

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: '>=2.5.0 <5.0.0'
  riverpod_annotation: '>=2.3.0 <5.0.0'

  # Firebase
  firebase_auth: '>=4.15.0 <7.0.0'
  firebase_storage: '>=11.6.0 <14.0.0'

  # Image
  flutter_image_compress: '>=2.4.0 <3.0.0'
  image_picker: '>=1.0.7 <2.0.0'
  cached_network_image: '>=3.3.0 <4.0.0'

  # Cache local
  hive: '>=2.2.0 <3.0.0'
  hive_flutter: '>=1.1.0 <2.0.0'
  path_provider: '>=2.1.0 <3.0.0'

  # Utils
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: '>=2.3.0 <5.0.0'
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
